version: '3.4'
services:
  sdd_poc_server:
    image: sdd_server_dev
    build:
      dockerfile: ./Dockerfile
    container_name: sdd_server_dev
    ports:
      - 80:80
    restart: always
    volumes:
      - ./src:/code/
      - ./configs/example_config.yaml:/usr/sdd_poc_server/runtime.yaml
    depends_on:
      - mongodb
    networks:
      - sdd-network
  mongodb:
    container_name: mongodb
    image: mongo:7.0.0-rc3 #mongodb/mongodb-community-server:6.0-ubi8
    #command: --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    networks:
      - sdd-network
    volumes:
      - mongodata:/data/db/
networks:
  sdd-network:
    driver: bridge

volumes:
  mongodata:
    external: true

    
