auth:
- auth_name: default
  auth_type: signed_headers
base_image: ubuntu_18_04_proxy_python_3_8
build_args:
- name: example
  required_arg: false
  type: string
meta:
  author: Oblivious
  author_email: hello@oblivious.ai
  git: https://github.com/ObliviousAI/UN-PET-Hackathon.git
  version: 0.1.0
paths:
  - access: admin
    path: /train_data
    short_description: endpoint to upload training data set
  - access: admin
    path: /test_data
    short_description: endpoint to upload test data set
  - access: admin
    path: /configure
    short_description: endpoint to configure parties
  - access: participant
    path: /opendp
    short_description: endpoint to run differentially private opendp transformations on data
  - access: participant
    path: /diffprivlib
    short_description: endpoint to train pipeline using diffprivlib differentially private models
  - access: participant
    path: /smartnoise_sql
    short_description: endpoint to query data using Smartnoise-sql
  - access: participant
    path: /smartnoise_synth
    short_description: endpoint to generate synthetic data using Smartnoise-synth
  - access: participant
    path: /budget
    short_description: endpoint to get epsilon
  - access: participant
    path: /accuracy
    short_description: endpoint to get accuracy
  - access: participant
    path: /score
    short_description: endpoint to get score
  - access: participant
    path: /submit
    short_description: endpoint to submit file for the competition
roles:
  - role_auth: default
    role_cardinality: 4
    role_description: the parties involved in generation of synthetic data
    role_name: participant
  - role_auth: default
    role_cardinality: 1
    role_description: the parties involved in generation of synthetic data
    role_name: admin
traffic:
  inbound:
    - name: main_io
      port: 80
      type: tcp
  outbound: 
    - name: slack
      port: 443
      type: tcp
      domain: hooks.slack.com
    - name: document_db
      port: 27017
      type: tcp
      domain: stage-un-g20-nov22.cluster-clagiea8p62e.eu-west-1.docdb.amazonaws.com
