runtime_args:
  settings:
    users:
      - username: Alice
        dataset: dataset_1
        epsilon_start: 10
        delta_start: 0.0004
    submit_limit: 300
    time_attack:
        method: "jitter" # or "stall"
        magnitude: 1
  
  #MDDB_DBNAME : datasets
  #MDDB_USER: "oblivious"
  #MDDB_PASS: "<mongo_pass>"
  #MDDB_URL: "stage-un-g20-nov22.cluster-clagiea8p62e.eu-west-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  #MDDB_PROT: "mongodb://" #"mongodb://" or "mongodb+srv://