runtime_args:
  settings:
    users:
    - user_name: Alice
      datasets_list:
      - dataset_name: "iris"
        max_epsilon: 10
        max_delta: 0.0001
        current_epsilon: 1
        current_delta: 0.000001
      - dataset_name: "penguin"
        max_epsilon: 5
        max_delta: 0.0005
        current_epsilon: 0.2
        current_delta: 0.0000001
    - user_name: Bob
      datasets_list:
      - dataset_name: "iris"
        max_epsilon: 10
        max_delta: 0.0001
        current_epsilon: 0
        current_delta: 0
    submit_limit: 300
    time_attack:
        method: "jitter" # or "stall"
        magnitude: 1
  
  #MDDB_DBNAME : datasets
  #MDDB_USER: "oblivious"
  #MDDB_PASS: "<mongo_pass>"
  #MDDB_URL: "stage-un-g20-nov22.cluster-clagiea8p62e.eu-west-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  #MDDB_PROT: "mongodb://" #"mongodb://" or "mongodb+srv://